### ISSUE TITLE
Errors - Cannot complete analysis

### ISSUE THREAD

**Issue by oceangirlri** [jDeters-USACE/Antecedent-Precipitation-Tool#28]
**No matter the dates or location entered the following errors occur:**

The APT cannot complete this analysis.

The following error occurred. Please close the APT and reboot.

Exception in Tkinter callback
Traceback (most recent call last):
  File "arc\anteProcess.py", line 191, in test_usgs_epqs_servers
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "arc\ant_GUI.py", line 773, in calculate_and_graph
  File "arc\ant_GUI.py", line 837, in get_inputs_unique
  File "arc\ant_GUI.py", line 1256, in calculate_or_add_batch
  File "arc\anteProcess.py", line 356, in __init__
  File "arc\anteProcess.py", line 204, in test_usgs_epqs_servers
Exception: The APT is unable to run if USGS Elevation Point Query Services are offline.

**Comment by jlgutenson** [comment]
Hi @oceangirlri, 

I hate to hear that you're having APT troubles!

The USGS Elevation Point Query Services may have been down when you tried running the APT. Sometimes you may just need to give it a couple of hours and it'll be back up. 

Also, this repo is no longer supported by USACE. Please email your questions or issues to APT-Report-Issue@usace.army.mil and they should be able to provide some assistance. If your issue persists, just let them know at that email address.

Thanks,
Joseph Gutenson
