### ISSUE TITLE
Can you help me connect?

### ISSUE THREAD

**Issue by gregthetech** [jDeters-USACE/Antecedent-Precipitation-Tool#3]
Please find below the output from running Antecedent Precipitation Tool.exe, from the cmd.exe.  My company IT department indicates that they are not blocking github and that there may be something that you can do to get me past the error and connect.

C:\Users\Gjimenez\Antecedent.Precipitation.Calculator (1)\Antecedent Precipitation Calculator>"Antecedent Precipitation Tool.exe"
Traceback (most recent call last):
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\connection.py", line 370, in connect
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\ssl.py", line 407, in wrap_socket
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\ssl.py", line 814, in __init__
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\ssl.py", line 1068, in do_handshake
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\adapters.py", line 449, in send
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jDeters-USACE/Antecedent-Precipitation-Tool/master/v/wbd (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\Python\WinPythonARC_dev_EPA\Antecedent_Precipitation_Tool.py", line 77, in <module>
  File "D:\Code\Python\WinPythonARC_dev_EPA\arc\get_all.py", line 129, in ensure_wbd_folder
  File "D:\Code\Python\WinPythonARC_dev_EPA\arc\get_files.py", line 208, in get_only_newer_version
  File "D:\Code\Python\WinPythonARC_dev_EPA\arc\get_files.py", line 97, in parse_version
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\api.py", line 75, in get
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\api.py", line 60, in request
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\sessions.py", line 533, in request
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\sessions.py", line 668, in send
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\sessions.py", line 646, in send
  File "D:\Code\Python\WinPythonARC_dev_EPA\WinPythonZero32\python-3.6.5\lib\site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jDeters-USACE/Antecedent-Precipitation-Tool/master/v/wbd (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
[13828] Failed to execute script Antecedent_Precipitation_Tool

C:\Users\Gjimenez\Antecedent.Precipitation.Calculator (1)\Antecedent Precipitation Calculator>

**Comment by tdesmara02** [comment]
I got the same issue from my work computer, then tried on my home computer where the internet security settings are more relaxed.  Doing that fixed my problem - hope this helps, or at least provides a hint of where the problem is going on.

This is a really nice tool!

**Comment by jlgutenson** [comment]
Hey @gregthetech, were you able to work out the issues you were having?
